config/routes.rb
Rails.application.routes.draw do
  resources :static_files
  resources :contents
  root "static_pages#top"
  get '/top', to: 'static_pages#top'
  get '/signup', to: 'users#new'
  get '/login', to: 'users#login_form'
  post '/login', to: 'users#login'
  get '/home', to: 'home#index'
  delete '/logout', to: 'users#destroy'
  get '/addresses', to: 'addresses#index'
  get '/contents', to: 'contents#index'
  get '/xxx/:content_id' ,to: 'present#show'
  resources :addresses
  resources :users
  get '/user', to: 'users#show'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/content.rb
class Content < ApplicationRecord
  validates :user_id, { presence:true }
  validates :title, { presence:true }
  validates :title, length: { maximum: 47 }
  validates :address_id, { presence:true }
  validates :sender, { presence:true }
  validates :send_at, { presence:true }
  validates :text, length: { maximum: 500 }
 
  belongs_to :user
  belongs_to :static_file
  belongs_to :address

  extend Enumerize
  enumerize :shared, in: { private: 0, public: 1 }
  enumerize :status, in: { wait: 0, success: 1, error: 2}
end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController
  before_action :logged_in_user
  before_action :set_content, only: [:show, :edit, :update, :destroy]

  # GET /contents
  # GET /contents.json
  def index
    if !current_user.admin.admin?
      @contents = Content.where(user_id: current_user.id)
    else
      @contents = Content.all
    end
    
    @contents = Content.paginate(page: params[:page]).order(id: "desc")
  end

  def upload
    @upload_file = UploadFile.new( params.require(:upload_file).permit(:name, :file) )
    @upload_file.save
    redirect_to action: 'index'
  end

  # GET /contents/1
  # GET /contents/1.json
  def show
  end

  # GET /contents/new
  def new
    @content = Content.new(content_params)
    @content.static_file = StaticFile.find_by(id: content_params[:static_file_id])
    @content.user = current_user
  end

  # GET /contents/1/edit
  def edit
  end

  # POST /contents
  # POST /contents.json
  def create
    @content = Content.new(content_params)

    respond_to do |format|
      if @content.save
        format.html { redirect_to @content, notice: 'コンテンツが投稿されました' }
        format.json { render :show, status: :created, location: @content }
      else
        format.html {
          @content.static_file = StaticFile.find_by(id: @content.static_file_id)
          render :new
        }
        format.json { render json: @content.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contents/1
  # PATCH/PUT /contents/1.json
  def update
    respond_to do |format|
      if @content.update(content_params)
        format.html { redirect_to @content, notice: '更新完了' }
        format.json { render :show, status: :ok, location: @content }
      else
        format.html { render :edit }
        format.json { render json: @content.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contents/1
  # DELETE /contents/1.json
  def destroy
    @content = Content.find(params[:id])
    @content.destroy
    respond_to do |format|
      format.html { redirect_to contents_url, notice: '消去しました' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_content
      @content = Content.where(user_id: current_user.id).find_by(id: params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def content_params
      params.require(:content).permit(:user_id, :title, :format, :static_file_id, :text, :address, :sender, :send_at, :post_at, :received_at, :shared,  :address_id)
    end
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/views/contents/_form.html.erb
<%= form_with(model: content, local: true) do |form| %>
  <% if content.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(content.errors.count, "error") %> prohibited this content from being saved:</h2>

      <ul>
      <% content.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% if current_user.admin.admin? %>
    <div class="field">
      <%= form.label :user_id %>
      <%= form.collection_select :user_id, user_options, :id, :name %>
    </div>
  <% else %>
    <%= form.hidden_field :user_id %>
  <% end %>

  <div class="content_edit">
    <%= form.label :title %><br>
    <div class="content_edit_title">
      <%= form.text_field :title, class: "content_edit_title_text_field" %>
    </div>
  
    <div class="content_edit_body">
      <div class="content_edit_image">
        <% if content.static_file.nil? %>
          コンテンツが投稿されていません
        <% elsif ['video/mp4', 'video/quicktime'].include?(content.static_file.mime_type) %>
          <video width="500px" height="337.5px" src="<%= content.static_file.content_file.url %>" controls></video>
        <% elsif ['image/jpeg', 'image/png', 'image/gif', 'image/bmp'].include?(content.static_file.mime_type) %>
          <img width="500px" height="337.5px" src="<%= content.static_file.content_file.url %>" alt="アップロードした画像"></img>
        <% elsif ['audio/mp3', 'audio/mp4'].include?(content.static_file.mime_type) %>
          <audio width="200px" src="<%= content.static_file.content_file.url %>" controls></audio>
        <% end %>
        <%= form.hidden_field :static_file_id %>
        <%= form.hidden_field :content_id %>
        <%= form.hidden_field :status %>
      </div>
      
      <div class="content_edit_detail">
        <%= form.label :address %><br>
        <%= form.collection_select :address_id, address_options, :id, :name, {prompt: ""}, {class: "content_edit_address"} %><br><br>
    
        <%= form.label :sender %><br>
        <%= form.text_field :sender, class: "content_edit_address" %><br><br>
      
        <%= form.label :send_at %><br>
        <div class="input-group date datetimepicker">
          <%= form.text_field :send_at, class: "form-control" %>
         <span class="input-group-addon">
             <span class="fa fa-calendar"></span>
         </span>
        </div>
      </div>
    </div>
    
    <div class="content_edit_text">
      <%= form.label :text %><br>
      <%= form.text_area :text,  class: "content_edit_text_area" %>
    </div>
  
    <div>
      <%= form.submit :class=>"content_edit_actions_btn" %>
    </div>
    
  </div>
<% end %>

app/views/contents/edit.html.erb
<% provide(:title, "コンテンツの編集") %>

<%= render 'form', content: @content %>

<div>
    <%= link_to 'Back', contents_path, class: "content_edit_back" %>
</div>

app/views/contents/index.html.erb
<% provide(:title, "投稿一覧") %>

<div class="content_detail">
  <% @contents.each do |content| %>
    <div class="content_thumbnail">
        <% if ['video/mp4', 'video/quicktime'].include?(content.static_file.mime_type) %>
          <video class="thumbnail", width="400px" height="270px" src="<%= content.static_file.content_file.url %>" controls></video>
        <% elsif ['image/jpeg', 'image/png', 'image/gif', 'image/bmp'].include?(content.static_file.mime_type) %>
          <img class="thumbnail", width="400px" height="270px" src="<%= content.static_file.content_file.url %>" alt="アップロードした画像"></img>
        <% elsif ['audio/mp3', 'audio/mp4'].include?(content.static_file.mime_type) %>
          <audio class="thumbnail", width="200px" src="<%= content.static_file.content_file.url %>" controls></audio>
        <% end %>
    </div>
    <div class="content_description">
      <span class="content_title_index"><%= content.title %></span><br><br>
      <span>&emsp;&emsp;<%= tm :content, :address %> : <%= content.address.name %></span><br>
      <span>&emsp;<%= tm :content, :sender %> : <%= content.sender %></span><br>
      <span><%= tm :content, :send_at %> : <%= simple_time(content.send_at) %></span><br>
      <span><%= tm :content, :sent_at %> : <%= simple_time(content.sent_at) %></span><br>
      <span><%= tm :content, :status %> : <%= content.status %></span><br><br>
      <%= link_to '詳細', content, class: 'content_btn content_btn_show' %>
      <%= link_to '編集', edit_content_path(content), class: 'content_btn content_btn_edit' %>
      <%= link_to '削除', content, class: 'content_btn content_btn_destroy', method: :delete, data: { confirm: 'このコンテンツを消去しますか?' } %>
    </div>
  <% end %>
</div>

<%= will_paginate %>

app/views/contents/new.html.erb
<% provide(:title, "コンテンツの投稿") %>

<%= render 'form', content: @content %>

<div>
  <%= link_to 'Back', home_path, class: "content_edit_back" %>
</div>

app/views/contents/show.html.erb
<% provide(:title, "コンテンツの詳細") %>

<div class="content_title_show">
  <%= @content.title %>
</div><br>

<div class="content_show">
  <div class="content_show_image">
    <% if ['video/mp4', 'video/quicktime'].include?(@content.static_file.mime_type) %>
      <video width="700px" height="472.5px" src="<%= @content.static_file.content_file.url %>" controls></video>
    <% elsif ['image/jpeg', 'image/png', 'image/gif', 'image/bmp'].include?(@content.static_file.mime_type) %>
      <img width="700px" height="472.5px" src="<%= @content.static_file.content_file.url %>" alt="アップロードした画像"></img>
    <% elsif ['audio/mp3', 'audio/mp4'].include?(@content.static_file.mime_type) %>
      <audio width="200px" src="<%= @content.static_file.content_file.url %>" controls></audio>
    <% end %>
  </div>
  
  <div class="content_show_detail">
    <p>&emsp;&emsp;<%= tm :content, :address %> : <%= @content.address.name %></p><br>
    <p>&emsp;<%= tm :content, :sender %> : <%= @content.sender %></p><br>
    <p><%= tm :content, :send_at %> : <%= simple_time(@content.send_at) %></p><br>
    <p><%= tm :content, :sent_at %> : <%= simple_time(@content.sent_at) %></p><br>
    <p>&emsp;&emsp;<%= tm :content, :format %> : <%= @content.static_file.mime_type %></p><br>
    <p><%= tm :content, :text %></p>
    <p class="content_text"><%= @content.text %></p><br>
  </div>
</div>

<div class="content_show_link">
  <%= link_to '編集', edit_content_path(@content), class: 'content_btn content_btn_edit' %>
  <%= link_to 'Back', contents_path, class: 'content_btn content_btn_back' %>
  <%= link_to '削除', @content, class: 'content_btn content_btn_destroy', method: :delete, data: { confirm: 'このコンテンツを消去しますか?' } %>
</div>