config/routes.rb
Rails.application.routes.draw do
  resources :static_files
  resources :contents
  root "static_pages#top"
  get '/top', to: 'static_pages#top'
  get '/signup', to: 'users#new'
  get '/login', to: 'users#login_form'
  post '/login', to: 'users#login'
  get '/home', to: 'home#index'
  delete '/logout', to: 'users#destroy'
  get '/addresses', to: 'addresses#index'
  get '/contents', to: 'contents#index'
  get '/xxx/:content_id' ,to: 'present#show'
  resources :addresses
  resources :users
  get '/user', to: 'users#show'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/static_file.rb
class StaticFile < ApplicationRecord
  validates :mime_type, { presence:true }
  validates :content_file, { presence:true }

  mount_uploader :content_file, ContentFileUploader
end

app/controllers/static_files_controller.rb
class StaticFilesController < ApplicationController
  before_action :logged_in_user
  before_action :set_static_file, only: [ :show, :edit, :update, :destroy]

  # GET /static_files
  # GET /static_files.json
  
  def index
    @static_file = StaticFile.new
    @static_files = StaticFile.paginate(page: params[:page]).order(id: "desc")
  end

  # GET /static_files/1
  # GET /static_files/1.json
  def show
  end

  # GET /static_files/new
  def new
    @static_file = StaticFile.new
  end

  # GET /static_files/1/edit
  def edit
  end

  # POST /static_files
  # POST /static_files.json
  def create
    @static_file = StaticFile.new(static_file_params)
    if @static_file.mime_type.blank?
      @static_file.mime_type = params[:static_file][:content_file].content_type
    end
    create_content = params['create_content'].to_i

    respond_to do |format|
      if @static_file.save
        format.html {
          if create_content != 1
            redirect_to @static_file, notice: 'Static file was successfully created.'
          else
            redirect_to new_content_url({ content: { static_file_id: @static_file.id }})
          end
        }
        format.json { render json: {message: 'success', itemId: @static_file.id}, status: 200 }
      else
        format.html { render :new }
        format.json { render json: @static_file.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /static_files/1
  # PATCH/PUT /static_files/1.json
  def update
    respond_to do |format|
      if @static_file.update(static_file_params)
        format.html { redirect_to @static_file, notice: 'Static file was successfully updated.' }
        format.json { render :show, status: :ok, location: @static_file }
      else
        format.html { render :edit }
        format.json { render json: @static_file.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /static_files/1
  # DELETE /static_files/1.json
  def destroy
    @static_file.destroy
    respond_to do |format|
      format.html { redirect_to static_files_url, notice: 'コンテンツを削除しました' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_static_file
      @static_file = StaticFile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def static_file_params
      params.require(:static_file).permit(:mime_type, :content_file )
    end
end

app/helpers/static_files_helper.rb
module StaticFilesHelper
end

app/views/static_files/_form.html.erb
<%= form_with(model: static_file, local: true) do |form| %>
  <% if static_file.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(static_file.errors.count, "error") %> prohibited this static_file from being saved:</h2>

      <ul>
      <% static_file.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :mime_type %>
    <%= form.text_field :mime_type %>
  </div>

  <div class="field">
    <%= form.label :content_file %>
    <%= form.file_field :content_file %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/static_files/edit.html.erb
<h1>Editing Static File</h1>

<%= render 'form', static_file: @static_file %>

<%= link_to 'Show', @static_file %> |
<%= link_to 'Back', static_files_path %>

app/views/static_files/index.html.erb
<h1>Static Files</h1>

<div class="contents-home">
  <%= form_for @static_file, html: {class:'dropzone', id: "static_file-dropzone"} do |f| %>
    <div class="dz-message needsclick">
      <h3>Drop file here</h3> or
      <strong>Click</strong> to upload
    </div>
    
    <div class="fallback">
      <%= f.file_field :image_url %>
      <%= f.submit 'upload the image' %>
    </div>
    <%= f.hidden_field :mime_type %>
    
  <% end %>

<table>
  <thead>
    <tr>
      <th>Mine type</th>
      <th>File name</th>
      <th>Data</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @static_files.each do |static_file| %>
      <tr>
        <td><%= static_file.mime_type %></td>
        <td><%= static_file.mime_type %></td>
        <td>
          <% if ['video/mp4', 'video/quicktime'].include?(static_file.mime_type) %>
            <td><video width="500px" src="<%= static_file.content_file.url %>" controls></video></td>
          <% elsif ['image/jpeg', 'image/png', 'image/gif', 'image/bmp'].include?(static_file.mime_type) %>
            <td><img width="200px" src="<%= static_file.content_file.url %>" alt="アップロードした画像"></img></td>
          <% elsif ['audio/mp3', 'audio/mp4'].include?(static_file.mime_type) %>
            <td><audio width="200px" src="<%= static_file.content_file.url %>" controls></audio></td>
          <% end %>
        </td>
      </tr>
      <tr>
        <td><%= link_to 'Show', static_file %></td>
        <td><%= link_to 'Edit', edit_static_file_path(static_file) %></td>
        <td><%= link_to 'Destroy', static_file, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= will_paginate %>

<br>

<%= link_to 'New Static File', new_static_file_path %>

app/views/static_files/new.html.erb
<h1>New Static File</h1>

<%= render 'form', static_file: @static_file %>

<%= link_to 'Back', static_files_path %>

app/views/static_files/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Mime type:</strong>
  <%= @static_file.mime_type %>
</p>

<p>
  <strong>Content File:</strong>
  <%= @static_file.content_file %>
</p>

<p>
  <strong>Preview:</strong>
  <div>
    <% if @static_file.mime_type == 'video/mp4' %>
      <video width="200px" src="<%= @static_file.content_file.url %>"></video>
    <% elsif @static_file.mime_type == 'image/jpeg' %>
      <img width="200px" src="<%= @static_file.content_file.url %>" alt="アップロードした画像"></img>
    <% end %>
  </div>
</p>

<%= link_to 'Edit', edit_static_file_path(@static_file) %> |
<%= link_to 'Back', static_files_path %>