config/routes.rb
Rails.application.routes.draw do
  resources :static_files
  resources :contents
  root "static_pages#top"
  get '/top', to: 'static_pages#top'
  get '/signup', to: 'users#new'
  get '/login', to: 'users#login_form'
  post '/login', to: 'users#login'
  get '/home', to: 'home#index'
  delete '/logout', to: 'users#destroy'
  get '/addresses', to: 'addresses#index'
  get '/contents', to: 'contents#index'
  get '/xxx/:content_id' ,to: 'present#show'
  resources :addresses
  resources :users
  get '/user', to: 'users#show'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | TimeCapsule</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= include_gon %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  
  <body>
  <% if logged_in? %>
    <div class="header-home">
      <a class="header-home-logo" href="/home">Time capsule</a>
      <ul>
        <li><%= link_to "登録宛先一覧", addresses_path, class: 'header-home-list' %></li>
        <li><%= link_to "投稿一覧", contents_path, class: 'header-home-list' %></li>
        <li><%= link_to "ユーザー情報", "/users/:user_id/edit", class: 'header-home-list' %></li>
        <li><%= link_to "ログアウト", logout_path, class: 'header-home-list', method: :delete %></li>
      </ul>
      
      <span class="success_msgs"> <% if notice %>
        <p class="alert alert-success" id="notice">
          <%= notice %> 
        </p> <% end %> </span>
        
      <script>
        $( document ).ready(function() {
          $('#notice').fadeOut(3000);
      });
      </script>
    </div>
    <div class="header-home-dami"></div>
  <% end %>

    <%= yield %>
    
  </body>
</html>